### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by rigid** [tgalal/python-axolotl#10]
i'm not sure if this really is an axolotl problem, but with yowsup and axolotl 0.1.34 (installed via pip) I get lots of these:
WARNING yowsup.layers.axolotl.layer: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
Is there some "encode('utf-8')" missing somewhere?

**Comment by bdbais** [comment]
I identify the problem with ' (apostrophe) and èéòàùì letters... I removed them from return message and it send it without that warning, I know this is not the solution, I'm looking better one.

**Comment by jlguardi** [comment]
which python version are you using? I'm using python2.7 and I haven't troubles by now with encodings.

**Comment by rigid** [comment]
@jlguardi 
```
# python -V
Python 2.7.10
```
here

**Comment by bdbais** [comment]
# python -V
Python 2.7.3

on raspberry, but I can use 3.5 too

# python3.5 -V
Python 3.5.0

**Comment by rigid** [comment]
i'm pretty sure that this is a yowsup issue. closing for now.
