### ISSUE TITLE
Migration to GitHub Actions CI?

### ISSUE THREAD

**Issue by offa** [tgalal/python-axolotl#42]
Are there any plans for a migration to GitHub Actions?

**Comment by offa** [comment]
ping @tgalal

**Comment by tgalal** [comment]
There wasn't, but I guess it depends. Would it be useful to you? And in what way?

**Comment by offa** [comment]
Not for me directly, but Travis has become unusable for open source projects, thus most are moving away. I was wondering if that's the case here too (if so, I can provide help or a PR).

It's more a general question without a concrete need for action though.

**Comment by tgalal** [comment]
Aha, thanks for clarifying. Yes, with travis out of the picture now it make sense to migrate to something else, and a PR for github actions would be much appreciated
